export const ADD_COIN = 'ADD_COIN';
export const SET_AVTORIZED = 'SET_AVTORIZED';

export const GET_EMPTY_IMAGE = 'GET_EMPTY_IMAGE';

export const SET_COUNTRIES = 'SET_COUNTRIES';
export const GET_COUNTRIES = 'GET_COUNTRIES';

export const SET_COMPOSITIONS = 'SET_COMPOSITIONS';
export const GET_COMPOSITIONS = 'GET_COMPOSITIONS';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const SET_TYPESOFQUALITY = 'SET_TYPESOFQUALITY';
export const GET_TYPESOFQUALITY = 'GET_TYPESOFQUALITY';

export const GET_CATEGORIES_IMAGES = 'GET_CATEGORIES_IMAGES';
export const SET_CATEGORIES_IMAGES = 'SET_CATEGORIES_IMAGES';

export const SET_CATALOG = 'SET_CATALOG';
export const GET_CATALOG = 'GET_CATALOG';
export const GET_COIN = 'GET_COIN';

export const SET_IMAGES = 'SET_IMAGES';
export const GET_IMAGES = 'GET_IMAGES';
export const GET_IMAGE = 'GET_IMAGE';